name: test
on: 
  workflow_dispatch:
    inputs:
      data:
        description: 'data'
        default: '4 2 2 6 8 5 4 9 10 4 0 11 6 8 2 12 12 5 2 2 12 12 10 4 5 5 2 10'
        required: true
      
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build application
        run: |
          python main.py ${{ github.event.inputs.data }}
